# Generated by Django 4.1.7 on 2023-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0006_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
